name: Run static analyzer

on:
  push:
    branches:
      - main
      - master
      - develop
      - "releases/**"
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  checks: write

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    name: Build clang analyzer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Boost
        id: install-boost
        uses: MarkusJx/install-boost@v2
        with:
          boost_version: 1.87.0
          platform_version: 20.04
          link: shared
