name: Format
on:
  pull_request:
    branches: [main]
jobs:
  format:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          
      - name: Install dependencies
        run: sudo apt-get install clang-tidy

      - name: Generating Compilation Database
        run: |
          mkdir build
          cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -S . -B build
          ln -s build/compile_commands.json src/

      - name: Check Compilation Database
        run: cat build/*

      - name: Download python script from clang-tidy sources
        run: wget https://github.com/llvm/llvm-project/blob/main/clang-tools-extra/clang-tidy/tool/run-clang-tidy.py

      - name: Format code
        run: clang-tidy -checks='modernize-use-override' -fix -p src/ --use-color
      
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Apply formatting changes
          branch: ${{ github.head_ref }}